[build]
builder = "NIXPACKS"
buildCommand = "npm install"

[deploy]
startCommand = "node bot.js"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production" 